//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListTv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalList
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Channel { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
