//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListTv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puff
    {
        public int Pid { get; set; }
        public Nullable<int> Progid { get; set; }
    
        public virtual Program Program { get; set; }
    }
}
